version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      aws-sdk:
        patterns: ['@aws-sdk/*']
      dev-tooling:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directories:
      - /infra/bootstrap
      - /infra/envs/dev
      - /infra/envs/prod
    schedule:
      interval: weekly
